server:
  port: 8000

spring:
  application:
    name: Lms-notification

    kafka:
      bootstrap-servers: localhost:9094
      consumer:
        group-id: "consumer-1"
      topic: notification-events
